# Change these first
owner: Shangjin-Xiao # Your GitHub organization or username, where this repository lives
repo: shangjinyun-state # The name of this repository

sites:
  - name: 上晋云
    url: https://www.shangjinyun.cn
  - name: 上晋的blog
    url: https://blog.shangjinyun.cn
  - name: 上晋云照片
    url: https://photo.shangjinyun.cn 
  - name: 上晋云文件
    url: https://hub.shangjinyun.cn
  - name: 上晋云AI
    url: https://ai.shangjinyun.cn
  - name: shangjinyun-global
    url: https://file.shangjinyun.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: state.shangjinyun.cn
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**上晋云**服务器状态 "
  introMessage: 您可以在此处查看上晋云的服务状态，上晋云有关储存的服务仅在周五-周日 6:00-23:00提供。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Shangjin-Xiao/shangjinyun-state/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
